export const toggleAllCheckbox = 'TOGGLE_ALL_CHECKBOX'
export const toggleNoCheckbox = 'TOGGLE_NO_CHECKBOX'
export const toggleOneCheckbox = 'TOGGLE_ONE_CHECKBOX'
export const toggleTwoCheckbox = 'TOGGLE_TWO_CHECKBOX'
export const toggleThreeCheckbox = 'TOGGLE_THREE_CHECKBOX'
